name = "RenewalDiD"
uuid = "168ba0f3-27c8-4f61-a62a-678154ba4d3f"
version = "0.0.2-DEV7"
authors = ["Mark Pritchard <mark.pritchard@ndm.ox.ac.uk>"]

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[extensions]
RenewalDiDMakieExt = "Makie"
RenewalDiDReverseDiffExt = "ReverseDiff"

[compat]
Aqua = "0.8"
CairoMakie = "0.11, 0.12, 0.13, 0.14, 0.15"
Compat = "3.47, 4.10"
DataFrames = "1"
Distributions = "0.25"
DistributionsAD = "0.6"
Documenter = "1"
DynamicPPL = "0.37, 0.38, 0.39"
MCMCChains = "7.6"
Makie = "0.20, 0.21, 0.22, 0.23, 0.24"
Mooncake = "0.4"
NaNMath = "1.1"
PrettyTables = "2, 3"
Random = "1"
ReverseDiff = "1"
StableRNGs = "1"
StatsBase = "0.33, 0.34"
Test = "1"
Turing = "0.40, 0.41, 0.42"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[targets]
docs = ["CairoMakie", "Documenter", "StableRNGs"]
test = ["Test", "Aqua", "CairoMakie", "Documenter", "Mooncake", "ReverseDiff", "StableRNGs", "Turing"]
